# Generated by Django 5.2.15 on 2026-07-06 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('chain_id', models.BigIntegerField(unique=True)),
                ('native_symbol', models.CharField(default='ETH', max_length=20)),
                ('explorer_url', models.URLField(blank=True)),
                ('is_testnet', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('required_confirmations', models.PositiveIntegerField(default=12)),
                ('block_time_seconds', models.FloatField(default=12.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cs_chain',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RpcProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('http_endpoint', models.URLField(max_length=500)),
                ('ws_endpoint', models.CharField(blank=True, max_length=500)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_second', models.PositiveIntegerField(default=10)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy'), ('unknown', 'Unknown')], default='unknown', max_length=12)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_reason', models.CharField(blank=True, max_length=500)),
                ('last_latency_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='chains.chain')),
            ],
            options={
                'db_table': 'cs_rpc_provider',
                'ordering': ['chain', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='RpcProviderHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ok', models.BooleanField()),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='chains.rpcprovider')),
            ],
            options={
                'db_table': 'cs_rpc_provider_health_log',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rpcprovider',
            index=models.Index(fields=['chain', 'is_active', 'priority'], name='cs_rpc_prov_chain_i_42b67f_idx'),
        ),
    ]
