# Generated by Django 5.2.15 on 2026-07-06 15:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chains', '0001_initial'),
        ('events', '0001_initial'),
        ('monitors', '0001_initial'),
        ('webhooks', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=15)),
                ('dedupe_key', models.CharField(max_length=200, unique=True)),
                ('group_key', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='events.blockchainevent')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'cs_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='alerts.alert')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cs_alert_note',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_types', models.JSONField(blank=True, default=list)),
                ('token_address', models.CharField(blank=True, default='', max_length=42)),
                ('min_amount_wei', models.DecimalField(blank=True, decimal_places=0, max_digits=78, null=True)),
                ('max_amount_wei', models.DecimalField(blank=True, decimal_places=0, max_digits=78, null=True)),
                ('from_address', models.CharField(blank=True, default='', max_length=42)),
                ('to_address', models.CharField(blank=True, default='', max_length=42)),
                ('spender_address', models.CharField(blank=True, default='', max_length=42)),
                ('topic0', models.CharField(blank=True, default='', max_length=66)),
                ('trigger_on', models.CharField(choices=[('confirmed', 'Confirmed events'), ('reverted', 'Reverted events (reorg)')], default='confirmed', max_length=10)),
                ('severity', models.CharField(blank=True, choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='', help_text="Blank inherits the event's severity.", max_length=10)),
                ('cooldown_seconds', models.PositiveIntegerField(default=0, help_text='Suppress repeat alerts for the same fingerprint for N seconds.')),
                ('group_window_seconds', models.PositiveIntegerField(default=0, help_text='Fold repeat alerts within N seconds into one grouped alert (debounce).')),
                ('notify_in_app', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=False)),
                ('notify_webhook', models.BooleanField(default=False)),
                ('telegram_enabled', models.BooleanField(default=False)),
                ('slack_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='chains.chain')),
                ('contract_monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='monitors.contractmonitor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wallet_monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='monitors.walletmonitor')),
                ('webhook', models.ForeignKey(blank=True, help_text='Deliver to this endpoint. Blank = all endpoints subscribed to alert.triggered.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_rules', to='webhooks.webhookendpoint')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'cs_alert_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alerts.alertrule'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['workspace', 'is_active'], name='cs_alert_ru_workspa_1964f6_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['workspace', 'status'], name='cs_alert_workspa_edea39_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['workspace', 'severity'], name='cs_alert_workspa_c0b65c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['workspace', 'created_at'], name='cs_alert_workspa_cefc76_idx'),
        ),
    ]
