# Generated by Django 5.2.15 on 2026-07-06 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chains', '0001_initial'),
        ('monitors', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_processed_block', models.BigIntegerField(default=0)),
                ('last_processed_hash', models.CharField(blank=True, max_length=66)),
                ('recent_blocks', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint', to='chains.chain')),
            ],
            options={
                'db_table': 'cs_block_checkpoint',
            },
        ),
        migrations.CreateModel(
            name='ReorgIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fork_block', models.BigIntegerField()),
                ('depth', models.PositiveIntegerField()),
                ('events_reverted', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorg_incidents', to='chains.chain')),
            ],
            options={
                'db_table': 'cs_reorg_incident',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('native_received', 'Native received'), ('native_sent', 'Native sent'), ('erc20_received', 'ERC-20 received'), ('erc20_sent', 'ERC-20 sent'), ('nft_received', 'NFT received'), ('nft_sent', 'NFT sent'), ('approval_created', 'Approval created'), ('approval_changed', 'Approval changed'), ('approval_revoked', 'Approval revoked'), ('approval_for_all', 'Approval for all (operator)'), ('contract_event', 'Contract event')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending confirmations'), ('confirmed', 'Confirmed'), ('reverted', 'Reverted (reorg)'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='pending', max_length=10)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_large', models.BooleanField(default=False)),
                ('block_number', models.BigIntegerField()),
                ('block_hash', models.CharField(max_length=66)),
                ('tx_hash', models.CharField(max_length=66)),
                ('tx_index', models.IntegerField(blank=True, null=True)),
                ('log_index', models.IntegerField(blank=True, null=True)),
                ('from_address', models.CharField(blank=True, default='', max_length=42)),
                ('to_address', models.CharField(blank=True, default='', max_length=42)),
                ('spender_address', models.CharField(blank=True, default='', max_length=42)),
                ('contract_address', models.CharField(blank=True, default='', max_length=42)),
                ('token_address', models.CharField(blank=True, default='', max_length=42)),
                ('token_symbol', models.CharField(blank=True, default='', max_length=32)),
                ('token_decimals', models.IntegerField(blank=True, null=True)),
                ('token_id', models.CharField(blank=True, default='', max_length=100)),
                ('amount_wei', models.DecimalField(blank=True, decimal_places=0, max_digits=78, null=True)),
                ('event_signature', models.CharField(blank=True, default='', max_length=300)),
                ('topic0', models.CharField(blank=True, default='', max_length=66)),
                ('decoded', models.JSONField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('decode_error', models.CharField(blank=True, default='', max_length=300)),
                ('confirmations_required', models.PositiveIntegerField(default=12)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='chains.chain')),
                ('contract_monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='monitors.contractmonitor')),
                ('wallet_monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='monitors.walletmonitor')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'cs_blockchain_event',
                'ordering': ['-block_number', '-log_index'],
                'indexes': [models.Index(fields=['chain', 'block_number'], name='cs_blockcha_chain_i_b89042_idx'), models.Index(fields=['tx_hash'], name='cs_blockcha_tx_hash_b45ece_idx'), models.Index(fields=['from_address'], name='cs_blockcha_from_ad_dc4e65_idx'), models.Index(fields=['to_address'], name='cs_blockcha_to_addr_eb9ecb_idx'), models.Index(fields=['token_address'], name='cs_blockcha_token_a_8b385d_idx'), models.Index(fields=['topic0'], name='cs_blockcha_topic0_aae8dd_idx'), models.Index(fields=['workspace', 'created_at'], name='cs_blockcha_workspa_5697ff_idx'), models.Index(fields=['status', 'chain'], name='cs_blockcha_status_279a9f_idx'), models.Index(fields=['workspace', 'event_type'], name='cs_blockcha_workspa_cf2296_idx')],
            },
        ),
    ]
