# Generated by Django 5.2.15 on 2026-07-06 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chains', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAbi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('abi', models.JSONField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abis', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'cs_contract_abi',
            },
        ),
        migrations.CreateModel(
            name='ContractMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(db_index=True, max_length=42)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('confirmations_override', models.PositiveIntegerField(blank=True, help_text="Overrides the chain's default confirmation count.", null=True)),
                ('last_processed_block', models.BigIntegerField(default=0)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('selected_events', models.JSONField(default=list, help_text='Event names from the ABI to monitor.')),
                ('topic_filters', models.JSONField(blank=True, default=dict, help_text='Per-event indexed-parameter filters: {event: {param: value}}.')),
                ('abi_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitors', to='monitors.contractabi')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='chains.chain')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'cs_contract_monitor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=120)),
                ('signature', models.CharField(max_length=300)),
                ('topic0', models.CharField(db_index=True, max_length=66)),
                ('abi_fragment', models.JSONField()),
                ('indexed_filters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='monitors.contractmonitor')),
            ],
            options={
                'db_table': 'cs_event_subscription',
            },
        ),
        migrations.CreateModel(
            name='MonitorCsvImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('report', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_imports', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'cs_monitor_csv_import',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(db_index=True, max_length=42)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('confirmations_override', models.PositiveIntegerField(blank=True, help_text="Overrides the chain's default confirmation count.", null=True)),
                ('last_processed_block', models.BigIntegerField(default=0)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing'), ('both', 'Both')], default='both', max_length=10)),
                ('event_types', models.JSONField(default=list, help_text='Categories: native_transfer, erc20_transfer, nft_transfer, approval')),
                ('token_contract', models.CharField(blank=True, default='', help_text='Optional ERC-20/721 contract filter.', max_length=42)),
                ('min_value_wei', models.DecimalField(blank=True, decimal_places=0, help_text='Ignore transfers below this raw value (wei / token base units).', max_digits=78, null=True)),
                ('large_tx_threshold_wei', models.DecimalField(blank=True, decimal_places=0, help_text='Flag transfers at/above this raw value as large.', max_digits=78, null=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='chains.chain')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'cs_wallet_monitor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='contractabi',
            constraint=models.UniqueConstraint(fields=('workspace', 'sha256'), name='uniq_workspace_abi'),
        ),
        migrations.AddIndex(
            model_name='contractmonitor',
            index=models.Index(fields=['chain', 'is_active'], name='cs_contract_chain_i_5958ce_idx'),
        ),
        migrations.AddIndex(
            model_name='contractmonitor',
            index=models.Index(fields=['workspace', 'created_at'], name='cs_contract_workspa_f5dcdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractmonitor',
            constraint=models.UniqueConstraint(fields=('workspace', 'chain', 'address'), name='uniq_contract_monitor'),
        ),
        migrations.AddConstraint(
            model_name='eventsubscription',
            constraint=models.UniqueConstraint(fields=('contract_monitor', 'signature'), name='uniq_monitor_event_signature'),
        ),
        migrations.AddIndex(
            model_name='walletmonitor',
            index=models.Index(fields=['chain', 'is_active'], name='cs_wallet_m_chain_i_f32343_idx'),
        ),
        migrations.AddIndex(
            model_name='walletmonitor',
            index=models.Index(fields=['workspace', 'created_at'], name='cs_wallet_m_workspa_319696_idx'),
        ),
        migrations.AddConstraint(
            model_name='walletmonitor',
            constraint=models.UniqueConstraint(fields=('workspace', 'chain', 'address'), name='uniq_wallet_monitor'),
        ),
    ]
