import type { Metadata } from "next";

export const metadata: Metadata = { title: "Privacy policy" };

export default function PrivacyPage() {
  return (
    <div className="container py-5" style={{ maxWidth: 780 }}>
      <span className="section-eyebrow">Legal</span>
      <h1 className="fw-bold mt-2 mb-1">Privacy Policy</h1>
      <p className="text-secondary small mb-5">Last updated: July 2026</p>

      <div className="d-grid gap-4 text-secondary">
        <section>
          <h5 className="text-body fw-semibold">1. What we collect</h5>
          <p className="mb-0">
            Account data (email, name, hashed password), workspace configuration (monitors,
            rules, webhook endpoints), and operational records generated by monitoring (events,
            alerts, delivery logs, audit logs). Public blockchain data we process — addresses,
            transactions, logs — is already public by nature.
          </p>
        </section>
        <section>
          <h5 className="text-body fw-semibold">2. What we never collect</h5>
          <p className="mb-0">
            Private keys, seed phrases or wallet credentials. ChainSentinel is strictly
            read-only and never has the ability to move funds or sign transactions.
          </p>
        </section>
        <section>
          <h5 className="text-body fw-semibold">3. How we use data</h5>
          <p className="mb-0">
            To operate the service: matching blockchain activity to your monitors, delivering
            alerts and webhooks you configured, securing accounts (rate limiting, session and
            audit logging), and sending transactional email (verification, resets, alert and
            summary emails you opted into). We do not sell personal data.
          </p>
        </section>
        <section>
          <h5 className="text-body fw-semibold">4. Retention</h5>
          <p className="mb-0">
            Blockchain events, webhook delivery logs and operational logs are pruned on rolling
            retention windows. Account data persists until you delete your account or
            workspace, after which associated monitoring data is removed.
          </p>
        </section>
        <section>
          <h5 className="text-body fw-semibold">5. Security</h5>
          <p className="mb-0">
            Passwords are hashed with modern algorithms, sessions use HttpOnly cookies, webhook
            secrets are encrypted at rest, and sensitive actions are audit-logged. Report
            security issues via the contact page — we respond quickly.
          </p>
        </section>
        <section>
          <h5 className="text-body fw-semibold">6. Third parties</h5>
          <p className="mb-0">
            Monitoring requires querying the RPC providers you configure; those providers see
            the addresses being queried. Email is delivered through the SMTP provider the
            deployment is configured with. No analytics trackers are embedded in this site.
          </p>
        </section>
        <section>
          <h5 className="text-body fw-semibold">7. Your rights</h5>
          <p className="mb-0">
            You can export monitor configuration as CSV, delete monitors, workspaces or your
            entire account, and request a copy of the personal data we hold via the contact
            page.
          </p>
        </section>
      </div>
    </div>
  );
}
