# Generated by Django 5.2.15 on 2026-07-06 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('secret_encrypted', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('event_types', models.JSONField(default=list)),
                ('max_retries', models.PositiveIntegerField(default=5)),
                ('timeout_seconds', models.PositiveIntegerField(default=10)),
                ('last_status', models.CharField(blank=True, default='', max_length=20)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'cs_webhook_endpoint',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('payload', models.JSONField()),
                ('idempotency_key', models.CharField(max_length=250, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('retrying', 'Retrying'), ('exhausted', 'Exhausted (gave up)')], db_index=True, default='pending', max_length=12)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=500)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('replay_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replays', to='webhooks.webhookdelivery')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='workspaces.workspace')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhookendpoint')),
            ],
            options={
                'db_table': 'cs_webhook_delivery',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['workspace', 'enabled'], name='cs_webhook__workspa_ac210c_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['workspace', 'status'], name='cs_webhook__workspa_337b55_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['endpoint', 'created_at'], name='cs_webhook__endpoin_a54e35_idx'),
        ),
    ]
